name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Ensure Terser is installed
        run: npm install terser --no-save
      - name: Build
        run: npm run build:github
      - name: Fix GitHub Pages
        run: node fix-github-pages.cjs
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Copy 404.html
        run: cp 404.html dist/404.html
      - name: Add .nojekyll file
        run: touch dist/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Mappen som innehåller byggfilerna
          branch: gh-pages # Grenen som GitHub Pages läser från
